config/routes.rb
Rails.application.routes.draw do
  root to: 'petclubs#index'
  
  resources :owners

  resources :pets

  resources :petclubs

end

app/models/owner.rb
class Owner < ActiveRecord::Base
	has_many :pets
	belongs_to :petclub
end

app/models/pet.rb
class Pet < ActiveRecord::Base
	belongs_to :owner
	has_many :petclubs
end

app/models/petclub.rb
class Petclub < ActiveRecord::Base
	has_many :pets
	belongs_to :owner
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_action :set_owner, only: [:show, :edit, :update, :destroy]

  # GET /owners
  # GET /owners.json
  def index
    @owners = Owner.all

  end

  # GET /owners/1
  # GET /owners/1.json
  def show
  end

  # GET /owners/new
  def new
    @owner = Owner.new
    @petclub = Petclub.all
    
  end

  # GET /owners/1/edit
  def edit
    @petclub = Petclub.all
   

  end

  # POST /owners
  # POST /owners.json
  def create
    @owner = Owner.new(owner_params)

    respond_to do |format|
      if @owner.save
        format.html { redirect_to @owner, notice: 'Owner was successfully created.' }
        format.json { render :show, status: :created, location: @owner }
      else
        format.html { render :new }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /owners/1
  # PATCH/PUT /owners/1.json
  def update
    respond_to do |format|
      if @owner.update(owner_params)
        format.html { redirect_to @owner, notice: 'Owner was successfully updated.' }
        format.json { render :show, status: :ok, location: @owner }
      else
        format.html { render :edit }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owners/1
  # DELETE /owners/1.json
  def destroy
    @owner.destroy
    respond_to do |format|
      format.html { redirect_to owners_url, notice: 'Owner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_owner
      @owner = Owner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def owner_params
      params.require(:owner).permit(:name, :petclub_id)
    end
end

app/controllers/petclubs_controller.rb
class PetclubsController < ApplicationController
  before_action :set_petclub, only: [:show, :edit, :update, :destroy]

  # GET /petclubs
  # GET /petclubs.json
  def index
    @petclubs = Petclub.all
  end

  # GET /petclubs/1
  # GET /petclubs/1.json
  def show
  @petclub = Petclub.new
  @pets = Pet.all
  end

  # GET /petclubs/new
  def new
    @petclub = Petclub.new
    @pets = Pet.all
  end

  # GET /petclubs/1/edit
  def edit
    @petclub = Petclub.new
    @pets = Pet.all
  end

  # POST /petclubs
  # POST /petclubs.json
  def create
    @petclub = Petclub.new(petclub_params)

    respond_to do |format|
      if @petclub.save
        format.html { redirect_to @petclub, notice: 'Petclub was successfully created.' }
        format.json { render :show, status: :created, location: @petclub }
      else
        format.html { render :new }
        format.json { render json: @petclub.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /petclubs/1
  # PATCH/PUT /petclubs/1.json
  def update
    respond_to do |format|
      if @petclub.update(petclub_params)
        format.html { redirect_to @petclub, notice: 'Petclub was successfully updated.' }
        format.json { render :show, status: :ok, location: @petclub }
      else
        format.html { render :edit }
        format.json { render json: @petclub.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /petclubs/1
  # DELETE /petclubs/1.json
  def destroy
    @petclub.destroy
    respond_to do |format|
      format.html { redirect_to petclubs_url, notice: 'Petclub was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_petclub
      @petclub = Petclub.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def petclub_params
      params.require(:petclub).permit(:name, :pet_id)
    end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.all
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
    @owner = Owner.all
  end

  # GET /pets/1/edit
  def edit
    @owner = Owner.all 
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:name, :owner_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/petclubs_helper.rb
module PetclubsHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>PetsDB</title>

  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootswatch/3.0.2/amelia/bootstrap.min.css">
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.0.2/css/font-awesome.min.css">

  <style>
    /* Only necessary if you are using navbar-fixed-top */
    body {
      padding-top: 50px;
    }
  </style>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to Rails.application.class.parent_name, root_url, :class => "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Petclubs", petclubs_url %></li>
        <li><%= link_to "Pets", pets_url %></li>
        <li><%= link_to "Owners", owners_url %></li>
        <li><a href="#">About</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>

  <div class="container">
    <% if notice.present? %>
      <div class="alert alert-dismissable alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= notice %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/owners/_form.html.erb
<%= form_for(@owner) do |f| %>
  <% if @owner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@owner.errors.count, "error") %> prohibited this owner from being saved:</h2>

      <ul>
      <% @owner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :petclub_id %><br>
    <%= f.collection_select :petclub_id, @petclubs, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/owners/edit.html.erb
<h1>Editing owner</h1>

<%= render 'form' %>

<%= link_to 'Show', @owner %> |
<%= link_to 'Back', owners_path %>

app/views/owners/index.html.erb
<h1>Listing owners</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Petclub</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @owners.each do |owner| %>
      <tr>
        <td><%= owner.name %></td>
        <td><%= owner.petclub.name %></td>
        <td><%= link_to 'Show', owner %></td>
        <td><%= link_to 'Edit', edit_owner_path(owner) %></td>
        <td><%= link_to 'Destroy', owner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Owner', new_owner_path %>

app/views/owners/new.html.erb
<h1>New owner</h1>

<%= render 'form' %>

<%= link_to 'Back', owners_path %>

app/views/owners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @owner.name %>
</p>

<p>
  <strong>Pet Club:</strong>
  <%= @owner.petclubs.name %>
</p> Owners In This Pet Club:
	<ul>
		<% @petclub.owner.each do |owner| %>
		<li> <%=owner.name %></li>
		<% end %>

	</ul>

</p>

<%= link_to 'Edit', edit_owner_path(@owner) %> |
<%= link_to 'Back', owners_path %>

app/views/petclubs/_form.html.erb
<%= form_for(@petclub) do |f| %>
  <% if @petclub.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@petclub.errors.count, "error") %> prohibited this petclub from being saved:</h2>

      <ul>
      <% @petclub.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :pet_id %><br>
    <%= f.collection_select :pet_id, @pets, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/petclubs/edit.html.erb
<h1>Editing petclub</h1>

<%= render 'form' %>

<%= link_to 'Show', @petclub %> |
<%= link_to 'Back', petclubs_path %>

app/views/petclubs/index.html.erb
<h1>Listing petclubs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Pet</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @petclubs.each do |petclub| %>
      <tr>
        <td><%= petclub.name %></td>
        <td><%= petclub.pets.name %></td>
        <td><%= link_to 'Show', petclub %></td>
        <td><%= link_to 'Edit', edit_petclub_path(petclub) %></td>
        <td><%= link_to 'Destroy', petclub, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Petclub', new_petclub_path %>

app/views/petclubs/new.html.erb
<h1>New petclub</h1>

<%= render 'form' %>

<%= link_to 'Back', petclubs_path %>

app/views/petclubs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @petclub.name %>
</p>

<p>
  <strong>Pet:</strong>
  <%= @pets.name %>
</p>
<p> PetClubs For Pets
	<ul>
		<%@petclub.pets.each do |pet| %>
		<li> <%= pet.name %> </li>
		<% end %>
	</ul>
</p>

<%= link_to 'Edit', edit_petclubs_path(@petclub) %>| 
<%= link_to 'Back', petclubs_path %>

app/views/pets/_form.html.erb
<%= form_for(@pet) do |f| %>
  <% if @pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
      <% @pet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :owner_id %><br>
    <%= f.collection_select :owner_id, @owner, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pets/edit.html.erb
<h1>Editing pet</h1>

<%= render 'form' %>

<%= link_to 'Show', @pet %> |
<%= link_to 'Back', pets_path %>

app/views/pets/index.html.erb
<h1>Listing pets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Owner</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pets.each do |pet| %>
      <tr>
        <td><%= pet.name %></td>
        <td><%= pet.owner.name %></td>
        <td><%= link_to 'Show', pet %></td>
        <td><%= link_to 'Edit', edit_pet_path(pet) %></td>
        <td><%= link_to 'Destroy', pet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pet', new_pet_path %>

app/views/pets/new.html.erb
<h1>New pet</h1>

<%= render 'form' %>

<%= link_to 'Back', pets_path %>

app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pet.name %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @pet.owner_id %>
</p>

<%= link_to 'Edit', edit_pet_path(@pet) %> |
<%= link_to 'Back', pets_path %>